/**
 * What the AI bros shout while they run you off the extraction pad.
 *
 * Tone target: confidently wrong on LinkedIn. They are not threatening you,
 * they are networking at you, and that is the joke — the danger is that they
 * physically will not stop coming.
 *
 * Plain array on purpose: adding a line is a one-line diff, and the mission
 * RNG picks from it, so the same commit always gets the same nonsense.
 */
export const AI_BRO_LINES: readonly string[] = [
  'have you tried just prompting it better',
  "this is basically AGI, I don't know what to tell you",
  "I don't really write code anymore",
  'we 10x\'d velocity last sprint',
  'honestly? junior devs are over',
  "it's not a wrapper, it's an orchestration layer",
  "I've been saying this since GPT-2",
  'let me get you in a room with our AI strategy lead',
  'we should fine-tune on our Slack',
  'the model just *gets* our codebase',
  'why are you still using branches',
  'I had it write the tests too so we\'re covered',
  'we\'re an AI-first org now, it\'s in the deck',
  'this whole repo could be one prompt',
  'I ran it through three models and took the average',
  'have you read the paper? I skimmed the abstract',
  'we\'re not hiring engineers, we\'re hiring context engineers',
  'my agent is currently refactoring prod',
  'commits are kind of a legacy concept',
  'I gave it access to the database to speed things up',
  'we should put an LLM in front of the git history',
  'the hallucinations are actually a feature for ideation',
  'I vibe-coded our auth layer over the weekend',
  'can we get this into the newsletter',
  'quick one — are you free for a 30?',
  'I think you\'re overthinking the architecture',
  'what if the CLI was just a chat box',
  'we benchmarked it against ourselves and won',
  'evals are a nice-to-have honestly',
  'I don\'t review the diffs, I review the vibes',
  'we\'re pre-revenue but post-AGI',
  'this is a solved problem, you just need better context',
  'I\'m thinking we skip staging entirely',
  'the agent said it was done so I merged it',
  'have you considered an MCP for that',
  'we\'re going to disrupt version control',
  'I put the whole monorepo in the context window',
  'my P0 is a thought leadership post',
  'let\'s take this offline and then never resolve it',
  'I asked it if the code was correct and it said yes',
  'we don\'t do standups, we do async agent updates',
  'this would be trivial with a bigger model',
  'I\'ve got a Notion doc that explains everything',
  'what if merge conflicts were just... a mindset',
  'I\'m not technical but I understand the vision',
  'we\'re seeing insane traction on this internally',
  'the roadmap is whatever the model suggests',
  'shipping is a state of mind',
  'I automated my job and now I attend meetings',
  'circling back on my earlier circle back',
  'genuinely I think typing is over',
  'we should hire someone to prompt full-time',
  'this is exactly like the mobile shift, trust me',
  'I forked it, renamed it, and now it\'s ours',
  'my cofounder is an agent, legally it\'s fine',
  'have you got five minutes for a quick sync about syncs',
  'we\'re calling it AI-native, the deck loved it',
  'I don\'t need tests, I have conviction',
  'the repo is basically just training data now',
  'what\'s your take on us pivoting to agents',
] as const;
